services:
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.21.0
    container_name: wss-api-swagger-ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/api/openapi.yaml
    volumes:
      - ./api/openapi.yaml:/api/openapi.yaml
    restart: unless-stopped